default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || 'storage/development.sqlite3' %>
  adapter: <%= ENV.fetch("DB_ADAPTER", "sqlite3") %>

test:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || 'storage/test.sqlite3' %>
  adapter: <%= ENV.fetch("DB_ADAPTER", "sqlite3") %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || 'storage/production.sqlite3' %>
  adapter: <%= ENV.fetch("DB_ADAPTER", "sqlite3") %>

